package org.aal.GUI;

import java.sql.Date;
import java.text.DecimalFormat;
import org.aal.entities.Album;
import org.aal.entities.Artista;
import org.aal.service.AlbumService;
import org.aal.service.ArtistaService;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * EliminarArtista.java
 *
 * Created on 25/09/2012, 09:45:23 AM
 */
/**
 *
 * @author Jose Luis
 */
public class AñadirDetalleArtista extends javax.swing.JFrame
{
     Artista artista;
     Album album = new Album();
     String nombreAlbum;
     String genero;
     String duracion;
     Float precio;
     Date fechaLanzamiento;
     int flagActualizacion;
     DecimalFormat format= new DecimalFormat("####,#");
     AlbumService albumService = new AlbumService();
     ArtistaService artistaService = new ArtistaService();
    /** Creates new form EliminarArtista */
    public AñadirDetalleArtista(Artista artista)
    {
        this.artista=artista;
        flagActualizacion=0;
        initComponents();
    }
    public AñadirDetalleArtista(Artista artista, Album album)
    {
        this.artista=artista;
        this.album=album;
        flagActualizacion=1;
        initComponents();
        botonAñadirDetalle.setText("Actualizar");
        nombreDelAlbum.setText(album.getNombreAlbum());
        generoDelAlbum.setText(album.getGenero());
        duracionDelAlbum.setText(album.getDuracion());
        fechaLanzamientoAlbum.setText(album.getFechaLanzamiento().toString());
        precioDelAlbum.setText(album.getPrecio().toString());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonAñadirDetalle = new javax.swing.JButton();
        nombreDelAlbum = new javax.swing.JTextField();
        generoDelAlbum = new javax.swing.JTextField();
        duracionDelAlbum = new javax.swing.JTextField();
        fechaLanzamientoAlbum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        precioDelAlbum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setText("Nombre del Album: ");

        jLabel3.setText("Género: ");

        jLabel4.setText("Duración:");

        jLabel5.setText("Fecha Lanzamiento:");

        botonAñadirDetalle.setText("Añadir");
        botonAñadirDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDetalleActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio del Album: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1))
                            .addGap(95, 95, 95)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(precioDelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(fechaLanzamientoAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(duracionDelAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(98, 98, 98)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreDelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(generoDelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(botonAñadirDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreDelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(generoDelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(duracionDelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fechaLanzamientoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(precioDelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(botonAñadirDetalle)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDetalleActionPerformed
        // TODO add your handling code here:
        nombreAlbum=nombreDelAlbum.getText();
        genero=generoDelAlbum.getText();
        duracion=duracionDelAlbum.getText();
        fechaLanzamiento=Date.valueOf(fechaLanzamientoAlbum.getText());
        precio=(Float.valueOf(precioDelAlbum.getText()));
        album.setNombreAlbum(nombreAlbum);
        album.setGenero(genero);
        album.setDuracion(duracion);
        album.setFechaLanzamiento(fechaLanzamiento);
        album.setPrecio(precio);
        album.setArtista(artista);
        if(flagActualizacion==0)
        {
        artistaService.updateArtista(artista);
        albumService.persistAlbum(album);
        }
        else
        {
            artistaService.updateArtista(artista);
            albumService.updateAlbum(album);
        }
        this.dispose();
    }//GEN-LAST:event_botonAñadirDetalleActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirDetalle;
    private javax.swing.JTextField duracionDelAlbum;
    private javax.swing.JTextField fechaLanzamientoAlbum;
    private javax.swing.JTextField generoDelAlbum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreDelAlbum;
    private javax.swing.JTextField precioDelAlbum;
    // End of variables declaration//GEN-END:variables
}